name: Flujo de trabajo de CI
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 nose coverage colorama
      - name: Lint con flake8 (no bloquea)
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics || true
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics || true
      - name: Ejecutar pruebas unitarias con nose
        env:
          PYTHONPATH: .
        run: |
          nosetests -v -w tests --with-coverage --cover-package=app
