name: Flujo de trabajo de CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Lint con flake8
        run: |
          # Si tu repo no tiene carpeta 'service', esto no fallará (solo mostrará 0 archivos)
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics || true
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics || true

      - name: Instalar herramientas de prueba (nose + plugins)
        run: |
          pip install nose nose-spec coverage colorama

      - name: Ejecutar pruebas unitarias con nose
        env:
          PYTHONPATH: .
        run: |
          nosetests -v -w tests --with-spec --spec-color --with-coverage --cover-package=app
